services:
  postgres:
    image: postgres:16-alpine
    container_name: sellify_postgres
    environment:
      POSTGRES_DB: sellify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - sellify_pg:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: sellify_backend
    environment:
      PORT: 3000
      DB_URL: ${DB_URL}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: sellify_frontend
    environment:
      VITE_API_URL: ${VITE_API_URL}
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  sellify_pg:
